name: 'My Docker Action'
description: 'A Docker action that does something with two numbers'
inputs:
  number1:
    description: 'The first number'
    required: true
    default: '0'
  number2:
    description: 'The second number'
    required: true
    default: '0'
outputs:
  result:
    description: 'The result of the operation'
    value: 'some_output_value'  # Replace with the actual output value
runs:
  using: 'docker'
  image: 'Dockerfile'  # Specify your Dockerfile or image
